[package]
name = "examples-http-axum-connect"
edition = "2024"

[dependencies]
axum = "0.8.8"
axum-connect = "0.5.3"
prost = "0.13.5"
tokio = { version = "1.48.0", features = ["macros"] }

[build-dependencies]
axum-connect-build = "0.5.3"
